name: Django CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:      
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.11' ]
    name: Build and test ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet coverage
          pip install --quiet -r requirements.txt
      - name: Run Tests
        run: |
          cd forum
          coverage run manage.py test --no-logs
      - name: Coverage report
        id: coverage_report
        shell: bash
        run: |
          mv forum/.coverage .
          cp forum/.coveragerc .
          echo 'REPORT<<EOF' >> $GITHUB_ENV         
          coverage report >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            Coverage report:
            ```
            ${{ env.REPORT }}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
      - name: json report
        run: |
          coverage json
          echo "COVERAGE=$(jq '.totals.percent_covered_display|tonumber' coverage.json)" >> $GITHUB_ENV
      - name: Create Awesome Badge
        if: ${{ github.ref == 'ref/heads/main' }}
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.COVERAGE_GIST_ID }}
          filename: wiwik.json
          label: Coverage
          message: ${{ env.COVERAGE }}%
          color: green